config/routes.rb
Rails.application.routes.draw do
  
  root 'landing_pages#home'

  get 'sessions/new'
  get 'users/new'
  
  get '/home', to: 'landing_pages#home'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'

  get '/newevent', to: 'events#new'
  post '/newevent', to: 'events#create'
  resources :users
  resources :events, only: [:index, :show, :create, :new]
  resources :event_attendees, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendees, foreign_key: 'attended_event_id'
  has_many :attendees, through: :event_attendees, foreign_key: 'attendee_id'

  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date > ?', DateTime.now) }

  validates :title, presence: true, length: 4..30
  validates :description, presence: true, length: 4..400
  validates :date, presence: true
  validates :location, presence: true, length: 4..50
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attended_events, through: :event_attendees
  attr_accessor :remember_token

  validates :name, presence: true, length: 4..20
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def upcoming_events
    attended_events.upcoming
  end

  def previous_events
    attended_events.past
  end

  def attending?(event)
    event.attendees.include?(self)
  end

  def attend!(event)
    event_attendees.create!(attended_event_id: event.id)
  end

  def cancel!(event)
    event_attendees.find_by(attended_event_id: event.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event = Event.find(params[:event_attendee][:attended_event_id])
    current_user.attend!(@event)
    redirect_to @event
  end

  def destroy
    @event = EventAttendee.find(params[:id]).attended_event
    current_user.cancel!(@event)
    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user, only: [:new]
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = 'Event created!'
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location, :description)
  end

  def signed_in_user
    redirect_to signin_path unless signed_in?
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      sign_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the Private Events!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        sign_in user
        @current_user = user
      end
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/events/_attend.html.erb
<% if signed_in? %>
	<%= form_for(current_user.event_attendees.build(attended_event_id: @event.id)) do |f| %>
	<%= f.hidden_field :attended_event_id %>
		<%= f.submit "Attend", class: "btn btn-sm btn-primary" %>
	<% end %>
<% end %>

app/views/events/_attend_cancel.html.erb
 
<% if signed_in? && current_user.attending?(@event) %> 
<%= render 'cancel' %>
<% else %>
<%= render 'attend' %>
<% end %>

app/views/events/_cancel.html.erb
<%= form_for(current_user.event_attendees.find_by(attended_event_id: @event.id),
html: { method: :delete }) do |f| %>
<%= f.submit "Cancel", class: "btn btn-sm btn-default" %>
<% end %>

app/views/events/index.html.erb
<div class="row">
  
    <h1>Future Events</h1>
  
  <div class='event-body'>
  <% Event.upcoming.each do |event| %>
    <div class='event'>

      <h3 class='featurette-heading'><%= event.title%></h3>
      <div class='event-body'>
      <p><%= event.description %></p>
      <div class='event-details'>
        <span>Event location: <%= event.location %></span>
        <span>Event date: <%= event.date.strftime("%Y/%m/%d") %><span>
      </div>
      </div>
      </div>
  <% end %>
</div>

<div class="row">
  
    <h1>Past Events</h1>
  
  <div class='event-body'>
  <%  Event.past.each do |event| %>
    <div class='event'>
      <h3 class='featurette-heading'><%= event.title%></h3>
      <div class='event-body'>
      <p><%= event.description %></p>
      <div class='event-details'>
        <span>Event location: <%= event.location %></span>
        <span>Event date: <%= event.date.strftime("%Y/%m/%d") %><span>
      </div>
      </div>
      </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="row new-event">
  <div class="col-md-6 form-new-user col-md-offset-3">
    
      <%= form_for(@event) do |f| %>
        <%= f.label :title, class: 'form-label' %><br>
        <%= f.text_area :title, class: "form-control" %><br>
        <%= f.label :description, class: 'form-label' %><br>
        <%= f.text_area :description, class: "form-control" %><br>
        <%= f.label :location, class: 'form-label' %><br>
        <%= f.text_area :location, class: "form-control" %><br>
        <%= f.label :date, class: 'form-label' %><br>
        <%= f.date_field :date, class: "form-control" %><br>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %> 
  </div>
</div> 

app/views/events/show.html.erb
<h1>Event Creator: <%= link_to @event.creator.name,user_path %></h1>

<h3 class='event-header'><%=@event.title %></h3>

<div class="row">
    <div class='event-page'>
      <p><%= @event.description %></p>
        <span>Event location: <%= @event.location %></span>
        <span>Event date: <%=  @event.date.strftime("%Y/%m/%d") %></span>

        <% if @event.attendees.any? %>
            <% @event.attendees.each do |attendee| %>
                <span class="attendee">
                Attendee:  <%= attendee.name %>
                </span>
                <br/>
            <% end %>
        <% else %>
            No attendees
        <% end %><br/>
</div>


    <div class="div">
    <%= render 'attend_cancel' %>       
    </div>

app/views/landing_pages/home.html.erb
    <main class="center jumbotron jumbotron-fluid img-background">
    <div class='main-div'>
      <h1>Plan your Events now</h1>
      <h3 class='home-header'>This is the home page for the
          <a href="#">Private Events</a> application.
      </h3>
      <% if signed_in? %>
      <% else %>
      <%= link_to "Create an Event", '/signin', class: "btn btn-lg btn-primary btn-lg" %>
      <% end %>
      </div>
    </main>

    <footer class="footer">
          <small>
              <a href="#">  Private Events created </a>
              by <a href="https://github.com/tundeiness/Private-Events">Olga Pelts & Tunde Oretade</a>
          </small>
          <nav>
              <ul>
                <li><%= link_to "About", '#' %></li>
                <li><%= link_to "Contact", '#' %></li>
              </ul>
          </nav>
    </footer>
</div>

app/views/landing_pages/signin.html.erb
<h1>Sign in</h1>

<div class='row'>
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(:landing_pages, url: signin_path) do |f| %>
      <div class='form-group'>

        <%= f.label :email, class:'form-label' %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :password, class:'form-label' %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.submit "Sign in", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "private event", home_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   home_path %></li>
            <li><%= link_to "Events",  events_path %></li>
        <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>   
            <li><%= link_to "Sign out", signout_path, method: :delete %>
          </li> 
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
<h1>Users: </h1>
  <div class="col-md-3 col-md-offset-4">  
      <% @users.each do |user| %>
      <div class="users-list">  
        <%= gravatar_for user %>
       <h2 class='users'> <%= user.name %> </h2>
       </div>
      <% end %>
  </div>
</div> 

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class='row'>
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <div class='form-group'>
      <%= render 'shared/error_messages' %>

        <%= f.label :name, class:'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, class:'form-label' %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :password, class:'form-label' %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation", class:'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
  
        <%= f.submit 'Sign up', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class='main'>
<div class='aside-col container'>
<div class='row'>
  <aside class='col-md-12'>
    <section class='user_info'>
    <%= gravatar_for @user %>
      <h1> 
        Welcome <%= @user.name %>
      </h1>
    </section>
  </aside>

  </div>
<button type='button' class='btn btn-dark btn-lg'><%= link_to 'Create event', new_event_path %></button>
</div>


<div class='events-col container'>
  <div class='row'>
    <div class='col-md-12'>
    <h2 class='events-header'> Events for <%= @user.name %></h2>
    
    <h3>Attending Events</h3>
    <table class="table">  
    <thead>
     <tr>
      <th  scope="col">Name</th>
      <th  scope="col">Location</th>
      <th  scope="col">Date</th>
     </tr>
    </thead>
      <% @user.attended_events.each do |attended| %>


       <tbody>
        <tr>
         <td><%= attended.title %></td>
         <td><%= attended.location %></td>
         <td><%= attended.date.strftime('%Y/%m/%d') %></td>
        </tr>
       </tbody> 
      <% end %>
      </table>  
    <h3>Future Events</h3>
 
    <% Event.upcoming.each do |event| %>
      <div class='event'>
        <h3 class='featurette-heading'><%= link_to event.title, event_path(event)%></h3>
          <div class='event-body'>
            <p><%= event.description%></p>
            <div class='event-details'>
            <span>Event location: <%= event.location%></span>
            <span>Event date: <%= event.date.strftime('%Y/%m/%d')%></span>
            </div>
          </div>
        </div>  
    <% end %>

    <h3>Past Events</h3>
 
    <% Event.past.each do |event| %>
      <div class='event'>
        <h3 class='featurette-heading'><%=event.title%></h3>
          <div class='event-body'>
            <p><%= event.description%></p>
            <div class='event-details'>
            <span>Event location: <%= event.location%></span>
            <span>Event date: <%= event.date.strftime('%Y/%m/%d')%></span>
            </div>
          </div>
        </div>  
    <% end %>

  </div>
</div> 
</div>